---
default:
  root_path: C:\Users\11473\OneDrive\Desktop\lxr
development:
  root_path: C:\Users\11473\OneDrive\Desktop\lxr
test:
  root_path: C:\Users\11473\OneDrive\Desktop\lxr
production:
  root_path: C:\Users\11473\OneDrive\Desktop\lxr
