---
default:
  root_path: C:\Users\11473\OneDrive\Desktop\G3下
development:
  root_path: C:\Users\11473\OneDrive\Desktop\G3下
test:
  root_path: C:\Users\11473\OneDrive\Desktop\G3下
production:
  root_path: C:\Users\11473\OneDrive\Desktop\G3下
